# Generated by Django 4.2.9 on 2024-01-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NewsPaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlenewsarticle",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
