# Generated by Django 4.2.9 on 2024-01-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NewsPaper", "0002_alter_googlenewsarticle_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlenewsarticle",
            name="description",
            field=models.CharField(max_length=800),
        ),
    ]
