# Generated by Django 4.2.9 on 2024-01-26 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("NewsPaper", "0003_alter_googlenewsarticle_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googlenewsarticle",
            name="description",
        ),
    ]
